# Default values for wordpress-awsRDS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  name: wordpress
 
image:
  repository: wordpress
  tag: 5.8.0-apache
  pullPolicy: IfNotPresent
  
replicaCount: 1

strategy:
  type: Recreate
        
       
service:
  type: NodePort
  port: 8081
  nodePort: 30036
  externalIPs: NODE_PORT_SERVICE_PUBLIC_IP
configmap:
  data: "version: apache"

mysqldb:
     # AWS RDS connection url
     host: WORDPRESS_DB_HOST
     # AWS RDS instance username
     username: WORDPRESS_DB_USER
secret:
  data:
     # AWS RDS instance password
     password: BASE64_ENCODED_PASSWORD

resources:
  requests:
     storage: 2Gi
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

capacity:
  storage: 4Gi
hostPath:
  path: "/mnt/data"
pv:
  name: wp-pv-name
sc:
  name: manual






