apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.sc.name }}
  capacity:
    storage: {{ .Values.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hostPath.path }}"

