apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: wordpress-frontend
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: wordpress
    tier: frontend
  externalIPs:
    - {{ .Values.service.externalIPs }}
  type: {{ .Values.service.type }}
